# Generated by Django 6.0.2 on 2026-05-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawLogCSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(blank=True, null=True)),
                ('uid', models.CharField(max_length=100, unique=True)),
                ('id_orig_h', models.GenericIPAddressField()),
                ('id_orig_p', models.IntegerField()),
                ('id_resp_h', models.GenericIPAddressField()),
                ('id_resp_p', models.IntegerField()),
                ('proto', models.CharField(max_length=20)),
                ('service', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('orig_bytes', models.BigIntegerField(blank=True, null=True)),
                ('resp_bytes', models.BigIntegerField(blank=True, null=True)),
                ('conn_state', models.CharField(max_length=20)),
                ('local_orig', models.BooleanField(blank=True, null=True)),
                ('local_resp', models.BooleanField(blank=True, null=True)),
                ('missed_bytes', models.IntegerField(blank=True, null=True)),
                ('history', models.CharField(blank=True, max_length=50, null=True)),
                ('orig_pkts', models.IntegerField(blank=True, null=True)),
                ('orig_ip_bytes', models.BigIntegerField(blank=True, null=True)),
                ('resp_pkts', models.IntegerField(blank=True, null=True)),
                ('resp_ip_bytes', models.BigIntegerField(blank=True, null=True)),
                ('tunnel_parents', models.TextField(blank=True, null=True)),
                ('label', models.TextField(blank=True, null=True)),
                ('detail_label', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
