# Generated by Django 6.0.2 on 2026-05-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_rawlogcsv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawlogcsv',
            old_name='detail_label',
            new_name='detailed_label',
        ),
        migrations.AlterField(
            model_name='rawlogcsv',
            name='conn_state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rawlogcsv',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rawlogcsv',
            name='id_orig_h',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='rawlogcsv',
            name='id_orig_p',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rawlogcsv',
            name='id_resp_h',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='rawlogcsv',
            name='id_resp_p',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rawlogcsv',
            name='local_orig',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rawlogcsv',
            name='local_resp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rawlogcsv',
            name='proto',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
