# Generated by Django 6.0.2 on 2026-05-10 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_rename_detail_label_rawlogcsv_detailed_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawWatchguardLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('log_type', models.CharField(blank=True, max_length=50, null=True)),
                ('device_sn', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TopReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_name', models.CharField(choices=[('top_blocked_countries', 'Top Countries Blocked by Geolocation'), ('top_blocked_advanced_malware_apt', 'Top Malware Blocked by APT Blocker'), ('top_blocked_botnet_sites', 'Top Botnet Sites Blocked by Botnet Detection'), ('top_blocked_clients', 'Top Clients Blocked by the Firebox'), ('top_blocked_destinations', 'Top Destinations Blocked by the Firebox'), ('top_blocked_url_categories', 'Top URL Categories Blocked by WebBlocker'), ('top_blocked_applications', 'Top Applications Blocked by Application Control'), ('top_blocked_application_categories', 'Top Application Categories Blocked by Application Control'), ('top_blocked_protocols', 'Top Network Protocols Blocked by the Firebox'), ('top_blocked_attacks', 'Top Attacks Blocked by the Firebox'), ('top_blocked_malware', 'Top Malware Blocked by the Firebox')], max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('connections', models.IntegerField(default=0)),
                ('bytes', models.BigIntegerField(default=0)),
                ('detail', models.TextField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('raw_data', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-connections'],
            },
        ),
    ]
