# Generated by Django 6.0.2 on 2026-06-18 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0005_customgroupfolderinfo_securityevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyslogLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('device_name', models.CharField(blank=True, max_length=100, null=True)),
                ('device_id', models.CharField(blank=True, max_length=100, null=True)),
                ('device_time', models.DateTimeField(blank=True, null=True)),
                ('log_type', models.CharField(choices=[('firewall', 'Firewall'), ('https-proxy', 'HTTPS Proxy'), ('http-proxy', 'HTTP Proxy'), ('tcp-udp-proxy', 'TCP UDP Proxy'), ('link-mon', 'Link Monitor'), ('loggerd', 'Loggerd'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('process_id', models.IntegerField(blank=True, null=True)),
                ('msg_id', models.CharField(blank=True, max_length=50, null=True)),
                ('action', models.CharField(choices=[('Allow', 'Allow'), ('Deny', 'Deny'), ('Block', 'Block'), ('Drop', 'Drop'), ('Unknown', 'Unknown')], default='Unknown', max_length=50)),
                ('from_zone', models.CharField(blank=True, max_length=100, null=True)),
                ('to_zone', models.CharField(blank=True, max_length=100, null=True)),
                ('protocol', models.CharField(blank=True, max_length=20, null=True)),
                ('src_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('dst_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('src_port', models.IntegerField(blank=True, null=True)),
                ('dst_port', models.IntegerField(blank=True, null=True)),
                ('geo_src', models.CharField(blank=True, max_length=10, null=True)),
                ('geo_dst', models.CharField(blank=True, max_length=10, null=True)),
                ('policy', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('app_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cat_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dstname', models.CharField(blank=True, max_length=255, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('raw_log', models.TextField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='detection_s_timesta_33da7f_idx'), models.Index(fields=['log_type'], name='detection_s_log_typ_17cc42_idx'), models.Index(fields=['action'], name='detection_s_action_f76f11_idx'), models.Index(fields=['src_ip'], name='detection_s_src_ip_2ce858_idx'), models.Index(fields=['dst_ip'], name='detection_s_dst_ip_2869a3_idx'), models.Index(fields=['msg_id'], name='detection_s_msg_id_2a1b33_idx')],
            },
        ),
    ]
