# Generated by Django 6.0.2 on 2026-06-21 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0006_sysloglog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyslogDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_date', models.DateField(unique=True)),
                ('file_name', models.CharField(max_length=255, unique=True)),
                ('file_path', models.TextField()),
                ('total_rows', models.IntegerField(default=0)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('size_mb', models.FloatField(default=0)),
                ('storage_type', models.CharField(default='local', max_length=50)),
                ('generated_by', models.CharField(default='manual', max_length=50)),
                ('status', models.CharField(default='success', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='securityevent',
            name='custom_group_folder_info',
        ),
        migrations.DeleteModel(
            name='Detection',
        ),
        migrations.RemoveField(
            model_name='logclassification',
            name='log',
        ),
        migrations.DeleteModel(
            name='RawLogCSV',
        ),
        migrations.DeleteModel(
            name='RawWatchguardLog',
        ),
        migrations.DeleteModel(
            name='CustomGroupFolderInfo',
        ),
        migrations.DeleteModel(
            name='SecurityEvent',
        ),
        migrations.DeleteModel(
            name='LogClassification',
        ),
        migrations.DeleteModel(
            name='RawLog',
        ),
    ]
