"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
SYSLOG_DATASET_DIR = BASE_DIR / "datasets" / "syslog"

load_dotenv(BASE_DIR / ".env")
# WATCHGUARD_BEARER_TOKEN = os.getenv("WATCHGUARD_BEARER_TOKEN")

# VPS_HOST = os.getenv("VPS_HOST")
# VPS_PORT = int(os.getenv("VPS_PORT") or 22)
# VPS_USER = os.getenv("VPS_USER")
# VPS_PRIVATE_KEY = os.getenv("VPS_PRIVATE_KEY")
# VPS_REMOTE_DIR = os.getenv("VPS_REMOTE_DIR", "/var/www/syslog-datasets")
# VPS_BASE_URL = os.getenv("VPS_BASE_URL")

# DATASET_API_KEY = os.getenv("DATASET_API_KEY")

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"





# ============================================================
# KONFIGURASI LANGSUNG
# ============================================================

WATCHGUARD_BEARER_TOKEN = "D2152BD48882DD969E701E4E2E6045C9"
DATASET_API_KEY = "D474537-17Y4-11261"
# RUN_SCHEDULER = True

# ============================================================
# KONFIGURASI VPS
# ============================================================

VPS_BASE_URL = "http://103.245.38.142/datasets"
VPS_HOST = "103.245.38.142"
VPS_PORT = 2222
VPS_USER = "csvuser"
VPS_REMOTE_DIR = "/var/www/syslog-datasets"
VPS_PRIVATE_KEY = "-----BEGIN OPENSSH PRIVATE KEY-----\nb3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZWQyNTUxOQAAACDyKZYxIZl+4ls465y0fx7Ia5FIYyvxH+Ph3nZfjnqp+gAAAJht7wOTbe8DkwAAAAtzc2gtZWQyNTUxOQAAACDyKZYxIZl+4ls465y0fx7Ia5FIYyvxH+Ph3nZfjnqp+gAAAEAtC+b/aXNu1+Lczn27DE8JqnNrx3dtP+1DCFi+QjM1q/IpljEhmX7iWzjrnLR/HshrkUhjK/Ef4+Hedl+Oeqn6AAAAEnJhaWx3YXktZGphbmdvLWNzdgECAw==\n-----END OPENSSH PRIVATE KEY-----"



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-=eu!d)%egr-)*=ap%(sclu-e7n)9r)+-8b-4(%f75cv@eeqv2s'
SECRET_KEY = os.environ.get("SECRET_KEY", "dev-secret-key")

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG = os.environ.get("DEBUG", "False") == "True"

# ALLOWED_HOSTS = ["*"]

ALLOWED_HOSTS = [
    "monitoringupatikpolindra.com",
    "www.monitoringupatikpolindra.com",
    "localhost",
    "127.0.0.1",
]

# ALLOWED_HOSTS = [
#     ".railway.app",
#     ".up.railway.app",
#     "localhost",
#     "127.0.0.1",
# ]

CSRF_TRUSTED_ORIGINS = [
    "https://monitoringupatikpolindra.com",
    "https://www.monitoringupatikpolindra.com",
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'corsheaders',

    'rest_framework',
    'rest_framework.authtoken',
    'api',
    "detection.apps.DetectionConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    'content-type',
    'authorization',
]
ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'ta_project_irgi',
#         'USER': 'postgres',
#         'PASSWORD': '112N4ZMU$',
#         'HOST': 'localhost',
#         'PORT': '5432',
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "monito44_ta_be",
        "USER": "monito44_tauser",
        "PASSWORD": "112N4ZMuS70F4",
        "HOST": "localhost",
        "PORT": "3306",
        "OPTIONS": {
            "charset": "utf8mb4",
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}

# DATABASES = {
#     "default": dj_database_url.config(
#         default=os.environ.get("DATABASE_URL")
#     )
# }



# INI UNTUK DI HOSTING
# DATABASE_URL = os.environ.get("DATABASE_URL")

# if not DATABASE_URL:
#     raise Exception("DATABASE_URL belum terbaca. Cek .htaccess atau environment variable.")

# DATABASES = {
#     "default": dj_database_url.parse(DATABASE_URL)
# }

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        # atau JWT
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# STATIC_URL = 'static/'
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"