# Generated by Django 6.0.2 on 2026-02-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('src_ip', models.CharField(max_length=16)),
                ('src_port', models.IntegerField(default=0)),
                ('dst_ip', models.CharField(max_length=16)),
                ('dst_port', models.IntegerField(default=0)),
                ('protocol', models.CharField(max_length=10)),
                ('bytes_sent', models.IntegerField(default=0)),
                ('bytes_received', models.IntegerField(default=0)),
                ('packets_sent', models.IntegerField(default=0)),
                ('packets_received', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('connection_status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
