# Generated by Django 6.0.2 on 2026-03-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_lograw'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkTraffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protokol', models.CharField(max_length=10)),
                ('durasi', models.IntegerField(default=0)),
                ('jumlah_bytes', models.IntegerField(default=0)),
                ('jumlah_packet', models.IntegerField(default=0)),
                ('status_koneksi', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=20)),
            ],
        ),
    ]
