# Generated by Django 6.0.2 on 2026-03-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_networktraffic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networktraffic',
            name='durasi',
            field=models.FloatField(default=0),
        ),
    ]
