# Generated by Django 6.0.2 on 2026-06-21 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_permission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogRaw',
        ),
        migrations.DeleteModel(
            name='NetworkTraffic',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
